# -*- coding: utf-8 -*-
"""DA - Working with Numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1roILVSq5wLA3wSYpDjKWmlZGqrfynlZn

# Assesment 1

Dataset:

https://github.com/TopsCode/Data_Analysis_2024/blob/main/ALL_CSV/banklist.
csv

1) Import pandas and read in the banklist.csv file into a dataframe called
banks.
"""

import pandas as pd
banks = pd.read_csv('/content/banklist.csv')

"""2) Show the head of the dataframe."""

# Show the first 5 rows of the dataframe
banks.head()

"""3) What are the column names?"""

# Get the column names
banks.columns

"""4) How many States (ST) are represented in this data set?"""

# Getting the number of unique states
num_states = banks['ST'].nunique()
num_states

"""5) Get a list or array of all the states in the data set."""

states = banks['ST'].unique()
states

"""6) What are the top 5 states with the most failed banks?"""

top_5_states = banks['ST'].value_counts().head(5)
top_5_states

"""7) What are the top 5 acquiring institutions?"""

top_5_acquirers = banks['Acquiring Institution'].value_counts().head(5)
top_5_acquirers

"""8) How many banks has the State Bank of Texas acquired? How many of
them were actually in Texas?
"""

# Number of banks acquired by the State Bank of Texas
num_acquired_by_sbt = banks[banks['Acquiring Institution'] == 'State Bank of Texas'].shape[0]

# Number of banks acquired by the State Bank of Texas in Texas
num_acquired_in_texas = banks[(banks['Acquiring Institution'] == 'State Bank of Texas') & (banks['ST'] == 'TX')].shape[0]

num_acquired_by_sbt, num_acquired_in_texas

"""9) What is the most common city in California for a bank to fail in?"""

# Get the most common city in California for a bank to fail
most_common_city_in_ca = banks[banks['ST'] == 'CA']['City'].value_counts().idxmax()
most_common_city_in_ca

"""# Assesment 2

Dataset:

https://github.com/TopsCode/Data_Analysis_2024/blob/main/ALL_CSV/historical_autom
obile_sales.csv

Q 1: Develop a Line chart using the functionality of pandas to show how
automobile sales fluctuate from year to year.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
df = pd.read_csv('/content/historical_automobile_sales.csv')

# Group by Year and calculate total sales for each year
yearly_sales = df.groupby('Year')['Automobile_Sales'].sum()

# Plot the line chart
plt.figure(figsize=(10,6))
yearly_sales.plot(kind='line', marker='o', color='b')
plt.title('Automobile Sales Fluctuations from Year to Year')
plt.xlabel('Year')
plt.ylabel('Total Automobile Sales')
plt.grid(True)
plt.show()

"""Q 2: Plot different lines for categories of vehicle type and analyze the trend
to answer the question Is there a noticeable difference in sales trends
between different vehicle types during recession periods?
"""

# Group by Year and Vehicle_Type to calculate total sales for each category per year
sales_by_type = df.groupby(['Year', 'Vehicle_Type'])['Automobile_Sales'].sum().unstack()

# Plotting line chart for each vehicle type
plt.figure(figsize=(10,6))
sales_by_type.plot(kind='line', marker='o')
plt.title('Sales Trends for Different Vehicle Types')
plt.xlabel('Year')
plt.ylabel('Total Automobile Sales')
plt.grid(True)
plt.legend(title='Vehicle Type')
plt.show()

